/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as CallbacksRouteImport } from './routes/callbacks'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TicketsRouteImport } from './routes/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbacksRoute = CallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/analytics': typeof AnalyticsRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/analytics': typeof AnalyticsRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/analytics': typeof AnalyticsRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisors'
    | '/analytics'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/conversations'
    | '/customers'
    | '/knowledge'
    | '/login'
    | '/overview'
    | '/policies'
    | '/rules'
    | '/settings'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisors'
    | '/analytics'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/conversations'
    | '/customers'
    | '/knowledge'
    | '/login'
    | '/overview'
    | '/policies'
    | '/rules'
    | '/settings'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/advisors'
    | '/analytics'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/conversations'
    | '/customers'
    | '/knowledge'
    | '/login'
    | '/overview'
    | '/policies'
    | '/rules'
    | '/settings'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CallbacksRoute: typeof CallbacksRoute
  CallsRoute: typeof CallsRoute
  ConversationsRoute: typeof ConversationsRoute
  CustomersRoute: typeof CustomersRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PoliciesRoute: typeof PoliciesRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbacks': {
      id: '/callbacks'
      path: '/callbacks'
      fullPath: '/callbacks'
      preLoaderRoute: typeof CallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorsRoute: AdvisorsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AvailabilityRoute: AvailabilityRoute,
  CallbacksRoute: CallbacksRoute,
  CallsRoute: CallsRoute,
  ConversationsRoute: ConversationsRoute,
  CustomersRoute: CustomersRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PoliciesRoute: PoliciesRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
