/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as CallbacksRouteImport } from './routes/callbacks'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TicketsRouteImport } from './routes/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbacksRoute = CallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRoute
  '/decisions': typeof DecisionsRoute
  '/escalations': typeof EscalationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRoute
  '/decisions': typeof DecisionsRoute
  '/escalations': typeof EscalationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisors': typeof AdvisorsRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/callbacks': typeof CallbacksRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRoute
  '/decisions': typeof DecisionsRoute
  '/escalations': typeof EscalationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/reference': typeof ReferenceRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisors'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/customers'
    | '/decisions'
    | '/escalations'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/overview'
    | '/policies'
    | '/reference'
    | '/settings'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisors'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/customers'
    | '/decisions'
    | '/escalations'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/overview'
    | '/policies'
    | '/reference'
    | '/settings'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/advisors'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/availability'
    | '/callbacks'
    | '/calls'
    | '/customers'
    | '/decisions'
    | '/escalations'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/overview'
    | '/policies'
    | '/reference'
    | '/settings'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CallbacksRoute: typeof CallbacksRoute
  CallsRoute: typeof CallsRoute
  CustomersRoute: typeof CustomersRoute
  DecisionsRoute: typeof DecisionsRoute
  EscalationsRoute: typeof EscalationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OverviewRoute: typeof OverviewRoute
  PoliciesRoute: typeof PoliciesRoute
  ReferenceRoute: typeof ReferenceRoute
  SettingsRoute: typeof SettingsRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbacks': {
      id: '/callbacks'
      path: '/callbacks'
      fullPath: '/callbacks'
      preLoaderRoute: typeof CallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorsRoute: AdvisorsRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  AvailabilityRoute: AvailabilityRoute,
  CallbacksRoute: CallbacksRoute,
  CallsRoute: CallsRoute,
  CustomersRoute: CustomersRoute,
  DecisionsRoute: DecisionsRoute,
  EscalationsRoute: EscalationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OverviewRoute: OverviewRoute,
  PoliciesRoute: PoliciesRoute,
  ReferenceRoute: ReferenceRoute,
  SettingsRoute: SettingsRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
