/**
 * lib/copy.ts — chapitre 55. Aucune chaine visible n'est ecrite dans un composant.
 */
export const copy = {
  brand: {
    name: "Nexus",
    tagline: "Voice support that respects your time.",
    version: "Version 1.0.0",
  },
  shell: {
    search: "Search",
    notifications: "Notifications",
    notificationsEmpty: "Nothing new.",
    account: "Account",
    signOut: "Sign out",
    language: "Language",
    collapseRail: "Collapse navigation",
    expandRail: "Expand navigation",
    secure: "SECURE",
    menu: { profile: "Your profile", security: "Security" },
  },
  login: {
    title: "Nexus",
    subtitle: "Sign in to your self-service portal.",
    submit: "Sign in",
    pending: "Signing in…",
    newHere: "New here? Create your secure sign-in.",
    notice: {
      manual: "You are signed out.",
      expired: "Your session expired. Sign in again.",
      password: "Your password was changed. Sign in with the new one.",
      revoked: "All devices were signed out. Sign in again.",
    },
  },
  signup: {
    title: "Create your sign-in",
    subtitle: "A password keeps your data out of other people's hands.",
    passwordLabel: "Password (at least 10 characters)",
    confirmLabel: "Confirm password",
    cinLabel: "Last 4 digits of your CIN",
    phoneLabel: "Phone number on the account",
    mismatch: "Those two passwords are not the same.",
    submit: "Create my sign-in",
    pending: "Creating your sign-in…",
    haveOne: "Already have a sign-in? Use it here.",
  },
  assistant: {
    title: "Private voice support, whenever you need it.",
    start: "Start conversation",
    end: "End",
    connecting: "Connecting…",
    enableAudio: "Enable assistant audio",
    assurance: {
      encrypted: "Encrypted end to end",
      audioOnly: "Audio only",
    },
    state: {
      disconnected: {
        label: "Ready when you are",
        detail: "Start a private conversation with the assistant.",
      },
      connecting: {
        label: "Opening a secure line",
        detail: "This usually takes a moment.",
      },
      preConnect: {
        label: "Getting your microphone ready",
        detail: "You can start speaking now.",
      },
      initializing: { label: "The assistant is joining", detail: "Almost there." },
      idle: { label: "Ready to listen", detail: "Speak whenever you are ready." },
      listening: { label: "Listening", detail: "Go ahead." },
      thinking: { label: "Working on it", detail: "Checking your account." },
      speaking: { label: "Speaking", detail: "You can interrupt at any time." },
      failed: {
        label: "Connection needs attention",
        detail: "End the conversation and try again.",
      },
    },
    stream: {
      heading: "LIVE CONVERSATION",
      assistant: "ASSISTANT",
      you: "YOU",
      willAppear: "Your conversation will appear here as you speak.",
      waiting: "Listening for the first words…",
      toolLabel: "Service action",
      toolDone: "Completed",
      toolFailed: "Failed",
    },
    controls: {
      mute: "Mute microphone",
      unmute: "Unmute microphone",
    },
    summary: {
      heading: "CONVERSATION SUMMARY",
      duration: "DURATION",
      turns: "TURNS",
      ended: "Conversation ended.",
      turnsPending: "Saving…",
      savedNote: "A written record of this conversation appears in your activity shortly.",
      resume: "Resume",
    },
    errors: {
      generic: "We could not open the line. Try again in a moment.",
      microphone: "We need access to your microphone to start a conversation.",
      timeout: "The assistant did not join in time. Try again.",
    },
  },
  activity: {
    heroLabel: "LAST CONVERSATION",
    when: "When",
    open: "Open conversation",
    tabs: {
      all: "All",
      conversations: "Conversations",
      requests: "Requests",
      callbacks: "Callbacks",
    },
    search: "Search activity",
    duration: "duration",
    turns: "turns",
    transcript: "TRANSCRIPT",
    callbackTime: "CALLBACK TIME",
    callbackWindow: "PREFERRED WINDOW",
    requestReference: "REFERENCE",
    requestCreated: "CREATED",
    requestUpdated: "UPDATED",
    requestPriority: "PRIORITY",
    requestCategory: "CATEGORY",
  },
  requests: {
    heroLabel: "NEEDS YOUR ATTENTION",
    open: "Open request",
    tabs: { active: "Active", resolved: "Resolved", all: "All" },
    search: "Search requests",
    reference: "REFERENCE",
    created: "CREATED",
    updated: "UPDATED",
    priority: "PRIORITY",
    category: "CATEGORY",
    timeline: "TIMELINE",
    empty: {
      title: "No requests here",
      body: "When you open a request with the assistant, it appears here.",
      action: "Show all requests",
    },
  },
  services: {
    plan: "YOUR PLAN",
    balances: "BALANCES",
    overAllowance: "You are over your monthly allowance.",
    renews: (date: string) => `Renews on ${date}`,
    activeSince: (date: string) => `Active since ${date}`,
  },
  billing: {
    amountDue: "AMOUNT DUE",
    invoices: "INVOICES",
    balances: "BALANCES",
    recharges: "RECHARGE HISTORY",
    bonus: (n: string) => `Plus ${n} bonus`,
    total: "TOTAL",
    issued: "ISSUED",
    due: "DUE",
    noInvoices: {
      title: "No invoices yet",
      body: "Every invoice appears here as soon as one is issued.",
    },
    noRecharges: {
      title: "No recharges yet",
      body: "When you top up, the record appears here.",
    },
  },
  help: {
    browse: "BROWSE BY TOPIC",
    contactLabel: "STILL NEED HELP?",
    contactBody:
      "The assistant can answer most questions instantly, and hand you to a specialist when it cannot.",
    startConversation: "Start a conversation",
    askInstead: "Ask the assistant instead",
    // Curated, static, and true: transcribed from lib/fixtures/help.ts at cleanup time.
    topics: [
      {
        title: "Getting started",
        body: "What the portal does and how the assistant works.",
        icon: "compass",
      },
      {
        title: "Talking to the assistant",
        body: "Start a conversation, mute, and what the assistant can do for you.",
        icon: "audio-lines",
      },
      {
        title: "Billing and invoices",
        body: "Invoices, balances, and what a charge means.",
        icon: "receipt-text",
      },
      {
        title: "Plans and add-ons",
        body: "What you have with us today and how it renews.",
        icon: "layers-2",
      },
      {
        title: "Privacy and data",
        body: "What is recorded, and what happens to it.",
        icon: "shield",
      },
      {
        title: "Accessibility",
        body: "Screen readers, keyboard use, and reduced motion.",
        icon: "accessibility",
      },
    ],
  },
  profile: {
    nav: {
      identity: "Identity",
      contact: "Contact",
      addresses: "Addresses",
      locale: "Language and region",
    },
    identity: "IDENTITY",
    contact: "CONTACT",
    addresses: "ADDRESSES",
    locale: "LANGUAGE AND REGION",
    changePhoto: "Change photo",
    remove: "Remove",
    edit: "Edit",
    copy: "Copy",
    locked: "This cannot be changed here. Ask the assistant if it is wrong.",
    reveal: "Reveal",
    hide: "Hide",
    billingAddress: "Billing address",
    serviceAddress: "Service address",
    sameAddress: "Service address is the same as billing address",
    unsaved: (n: number) => `${n} unsaved change${n === 1 ? "" : "s"}`,
    discard: "Discard",
    save: "Save changes",
    saved: "Profile updated",
    customerSince: (date: string) => `Customer since ${date}`,
    fields: {
      fullName: "Full name",
      preferredName: "Preferred name",
      dateOfBirth: "Date of birth",
      reference: "Customer reference",
      email: "Email",
      phone: "Phone",
      language: "Language",
      region: "Region",
      timeZone: "Time zone",
      dateFormat: "Date format",
      numberFormat: "Number format",
    },
  },
  preferences: {
    nav: {
      appearance: "Appearance",
      voice: "Voice and audio",
    },
    appearance: "APPEARANCE",
    voice: "VOICE AND AUDIO",
    density: "Density",
    densities: ["Comfortable", "Compact"],
    textSize: "Text size",
    textSizes: ["Default", "Large"],
    switches: {
      captions: {
        label: "Show captions by default",
        description: "Captions appear under the assistant while it speaks.",
      },
      reduceMotion: {
        label: "Reduce motion",
        description: "Slows the assistant visual and removes non-essential animation.",
      },
    },
    reduceMotionNote:
      "Applies across the portal immediately. The assistant visual follows your system setting.",
  },
  security: {
    nav: {
      signIn: "Sign-in",
      sessions: "Active sessions",
      activity: "Recent activity",
    },
    signIn: "SIGN-IN",
    sessions: "ACTIVE SESSIONS",
    activity: "RECENT ACTIVITY",
    password: "Password",
    changePassword: "Change password",
    currentPassword: "Current password",
    newPassword: "New password",
    passwordRule: "At least 10 characters. Changing it signs you out everywhere.",
    savePassword: "Change password",
    savingPassword: "Changing…",
    passwordChangedSignOut: "Password changed. Signing you out…",
    revokedSignOut: "Signing out every device…",
    revokedCount: (n: number) => `${n} session${n === 1 ? "" : "s"} signed out.`,
    lastChanged: (when: string) => `Last changed ${when}`,
    lastChangedNever: "Never changed",
    thisDevice: "This device",
    signOutAll: "Sign out of every device",
    signedIn: "Signed in",
  },
  about: {
    tagline: "Voice support that respects your time.",
    howHeading: "HOW THE ASSISTANT WORKS",
    canHeading: "WHAT IT CAN DO",
    cannotHeading: "WHAT IT CANNOT DO",
    dataHeading: "YOUR DATA",
    dataBody:
      "Your voice is never stored as audio. A masked, written record of each conversation is kept so you and our advisors can refer back to it. Nothing you say is used to train anyone else's assistant.",
    how: [
      {
        n: "01",
        t: "You speak",
        b: "Your voice is streamed over an encrypted connection. Nothing is recorded as audio.",
      },
      {
        n: "02",
        t: "It listens",
        b: "Your words are turned into text so the assistant can understand what you need.",
      },
      {
        n: "03",
        t: "It acts",
        b: "When it needs information from your account, it asks the system directly and shows you what it did.",
      },
      {
        n: "04",
        t: "You confirm",
        b: "Before anything changes, it tells you what it is about to do. You can stop it at any time.",
      },
    ],
    can: [
      "Look up your account",
      "Update your details",
      "Explain your invoices",
      "Open and track requests",
      "Schedule a callback",
      "Hand you to a specialist",
    ],
    cannot: [
      "Make payments on your behalf",
      "Access other customers' data",
      "Change your password",
      "Speak to anyone but you",
      "Record video or your screen",
      "Keep listening after you end a call",
    ],
    footer: ["Terms", "Privacy", "Accessibility"],
  },
  empty: {
    activityA: {
      title: "No activity yet",
      body: "When you talk to the assistant, every conversation appears here so you can come back to it.",
      action: "Start your first conversation",
    },
    filtered: {
      title: "Nothing matches",
      body: "Try a different search or clear the filters.",
      action: "Clear filters",
    },
    generic: "Nothing here yet.",
  },
  common: {
    back: "Back",
    tryAgain: "Try again",
    close: "Close",
    loading: "Loading",
    couldNotLoad: "We could not load this",
    pagination: "Pages",
    previous: "Previous page",
    next: "Next page",
    pageOf: (page: number, pages: number, total: number) =>
      `Page ${page} of ${pages} · ${total} item${total === 1 ? "" : "s"}`,
  },
  labels: {
    // conversation.call_sessions.final_disposition
    disposition: {
      resolved: "Resolved",
      escalated: "Passed to a specialist",
      dropped: "Disconnected",
      abandoned: "Ended early",
    },
    channel: { voice: "Voice", whatsapp: "WhatsApp", web: "Web", chat: "Chat" },
    // ticketing.tickets.status — five values (copy.requests.status had four)
    requestStatus: {
      open: "Received",
      in_progress: "In progress",
      pending: "Waiting on us",
      resolved: "Resolved",
      closed: "Closed",
    },
    requestCategory: {
      network_complaint: "Network",
      formal_complaint: "Formal complaint",
      technical: "Technical",
      billing: "Billing",
      other: "Other",
    },
    priority: { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" },
    invoiceStatus: {
      draft: "Draft",
      issued: "Issued",
      paid: "Paid",
      partial: "Partly paid",
      overdue: "Overdue",
      disputed: "Disputed",
      void: "Cancelled",
    },
    balanceType: { main: "Credit", data: "Data", voice: "Calls", sms: "Texts" },
    rechargeChannel: {
      app: "App",
      web: "Web",
      ussd: "USSD",
      scratch_card: "Scratch card",
      agent: "In store",
    },
    notificationChannel: { sms: "Text message", whatsapp: "WhatsApp", email: "Email" },
    notificationStatus: { queued: "Queued", sent: "Sent", failed: "Not delivered" },
    callbackStatus: { pending: "Scheduled", completed: "Done", cancelled: "Cancelled" },
    speaker: { caller: "You", agent: "Assistant" },
  },
  notificationTemplates: {
    // Extend as templates appear; unknown codes fall back to genericMessage.
    invoice_ready: "Your invoice is ready",
    payment_received: "We received your payment",
    payment_failed: "A payment did not go through",
    plan_changed: "Your plan was changed",
    ticket_update: "An update on one of your requests",
    callback_scheduled: "We scheduled a call back",
  },
  notifications: {
    heading: "RECENT MESSAGES",
    genericMessage: "A message about your account",
    empty: "Nothing new.",
  },
  errors: {
    notFoundTitle: "We could not find that page",
    notFoundBody: "The page may have moved, or the link may be out of date.",
    brokenTitle: "This page did not load",
    brokenBody: "Something went wrong on our side. Try again, or go back to the start.",
    goHome: "Go to the assistant",
    signedOut: "You have been signed out.",
    sessionExpired: "Your session has expired. Sign in again.",
  },
} as const;
