"""Importing this package registers every table on Base.metadata (used by Alembic)."""
from persistence.models import (
    audit,
    auth,
    billing,
    conversation,
    crm,
    execution,
    knowledge,
    ocs,
    oss,
    policy,
    portal_identity,
    provisioning,
    reference,
    routing,
    sim,
    ticketing,
)

__all__ = [
    "AgentUsageEvent",
    "audit",
    "auth",
    "billing",
    "conversation",
    "crm",
    "execution",
    "knowledge",
    "ocs",
    "oss",
    "policy",
    "portal_identity",
    "provisioning",
    "reference",
    "routing",
    "sim",
    "ticketing",
]
from persistence.models.conversation import AgentUsageEvent
