/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalAboutRouteImport } from './routes/_portal/about'
import { Route as PortalActivityRouteImport } from './routes/_portal/activity'
import { Route as PortalAssistantRouteImport } from './routes/_portal/assistant'
import { Route as PortalBillingRouteImport } from './routes/_portal/billing'
import { Route as PortalHelpRouteImport } from './routes/_portal/help'
import { Route as PortalPreferencesRouteImport } from './routes/_portal/preferences'
import { Route as PortalProfileRouteImport } from './routes/_portal/profile'
import { Route as PortalRequestsRouteImport } from './routes/_portal/requests'
import { Route as PortalSecurityRouteImport } from './routes/_portal/security'
import { Route as PortalServicesRouteImport } from './routes/_portal/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAboutRoute = PortalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PortalRoute,
} as any)
const PortalActivityRoute = PortalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssistantRoute = PortalAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelpRoute = PortalHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPreferencesRoute = PortalPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSecurityRoute = PortalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalRoute,
} as any)
const PortalServicesRoute = PortalServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/about': typeof PortalAboutRoute
  '/activity': typeof PortalActivityRoute
  '/assistant': typeof PortalAssistantRoute
  '/billing': typeof PortalBillingRoute
  '/help': typeof PortalHelpRoute
  '/preferences': typeof PortalPreferencesRoute
  '/profile': typeof PortalProfileRoute
  '/requests': typeof PortalRequestsRoute
  '/security': typeof PortalSecurityRoute
  '/services': typeof PortalServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/about': typeof PortalAboutRoute
  '/activity': typeof PortalActivityRoute
  '/assistant': typeof PortalAssistantRoute
  '/billing': typeof PortalBillingRoute
  '/help': typeof PortalHelpRoute
  '/preferences': typeof PortalPreferencesRoute
  '/profile': typeof PortalProfileRoute
  '/requests': typeof PortalRequestsRoute
  '/security': typeof PortalSecurityRoute
  '/services': typeof PortalServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_portal/about': typeof PortalAboutRoute
  '/_portal/activity': typeof PortalActivityRoute
  '/_portal/assistant': typeof PortalAssistantRoute
  '/_portal/billing': typeof PortalBillingRoute
  '/_portal/help': typeof PortalHelpRoute
  '/_portal/preferences': typeof PortalPreferencesRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/requests': typeof PortalRequestsRoute
  '/_portal/security': typeof PortalSecurityRoute
  '/_portal/services': typeof PortalServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/about'
    | '/activity'
    | '/assistant'
    | '/billing'
    | '/help'
    | '/preferences'
    | '/profile'
    | '/requests'
    | '/security'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/about'
    | '/activity'
    | '/assistant'
    | '/billing'
    | '/help'
    | '/preferences'
    | '/profile'
    | '/requests'
    | '/security'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_portal/about'
    | '/_portal/activity'
    | '/_portal/assistant'
    | '/_portal/billing'
    | '/_portal/help'
    | '/_portal/preferences'
    | '/_portal/profile'
    | '/_portal/requests'
    | '/_portal/security'
    | '/_portal/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/about': {
      id: '/_portal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PortalAboutRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/activity': {
      id: '/_portal/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof PortalActivityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/assistant': {
      id: '/_portal/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof PortalAssistantRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/billing': {
      id: '/_portal/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/help': {
      id: '/_portal/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PortalHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/preferences': {
      id: '/_portal/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PortalPreferencesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/requests': {
      id: '/_portal/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/security': {
      id: '/_portal/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof PortalSecurityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/services': {
      id: '/_portal/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PortalServicesRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAboutRoute: typeof PortalAboutRoute
  PortalActivityRoute: typeof PortalActivityRoute
  PortalAssistantRoute: typeof PortalAssistantRoute
  PortalBillingRoute: typeof PortalBillingRoute
  PortalHelpRoute: typeof PortalHelpRoute
  PortalPreferencesRoute: typeof PortalPreferencesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalSecurityRoute: typeof PortalSecurityRoute
  PortalServicesRoute: typeof PortalServicesRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAboutRoute: PortalAboutRoute,
  PortalActivityRoute: PortalActivityRoute,
  PortalAssistantRoute: PortalAssistantRoute,
  PortalBillingRoute: PortalBillingRoute,
  PortalHelpRoute: PortalHelpRoute,
  PortalPreferencesRoute: PortalPreferencesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalSecurityRoute: PortalSecurityRoute,
  PortalServicesRoute: PortalServicesRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
